using System;
using PRISM;

namespace MTDBConsole
{
    public class CommandOptions
    {
        [Option("m", "MzidListPath", Required = true, ArgPosition = 1, HelpText = "Path to a text file that contains the path to all mzid files to be included in database creation. (One path per line)")]
        public string MzidListPath { get; set; }

        [Option("d", "DatabasePath", Required = true, ArgPosition = 2, HelpText = "Path for database being generated by MTDB Creator.")]
        public string DatabasePath { get; set; }

        public void OutputSetOptions()
        {
            Console.WriteLine("Using options:");

            Console.WriteLine("MzidListPath: " + MzidListPath);
            Console.WriteLine("DatabasePath: " + DatabasePath);

        }

        public bool ValidateArgs()
        {
            if (string.IsNullOrWhiteSpace(MzidListPath))
            {
                Console.WriteLine("Mzid List file must be defined");
                return false;
            }

            if (string.IsNullOrWhiteSpace(MzidListPath))
            {
                Console.WriteLine("Database file path to create must be defined");
                return false;
            }

            return true;
        }

    }
}
