using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CommandLine;

namespace MTDBConsole
{
	public class CommandOptions
	{
		[Option('m', "MzidListPath", Required = true, HelpText = "Path to a text file that contains the path to all mzid files to be included in database creation. (One path per line)")]
		public string MzidListPath { get; set; }

		[Option('d', "DatabasePath", Required = true, HelpText = "Path for database being generated by MTDB Creator.")]
		public string DatabasePath { get; set; }
	}
}
