//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDBCreator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTDBCreator.StoredQueries", typeof(StoredQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon databaseCreator {
            get {
                object obj = ResourceManager.GetObject("databaseCreator", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE dbo.GetMassTagMatchCount
        ///(		
        ///	@MinimumHighNormalizedScore float = 0,	
        ///	@MinimumPMTQualityScore decimal(9,5) = 0,
        ///	@MinimumHighDiscriminantScore real = 0,		
        ///	@MinimumPeptideProphetProbability real = 0
        ///)
        ///As		
        ///	
        ///SELECT 
        ///		Mass_Tag_ID
        ///FROM 
        ///		T_Mass_Tags AS MT	
        ///WHERE 
        ///		IIF( 
        ///			@MinimumPMTQualityScore &lt;&gt; 0,			
        ///				IIF( ISNULL(MT.PMT_Quality_Score)=TRUE, 0, MT.PMT_Quality_Score) &gt;= @MinimumPMTQualityScore,
        ///				TRUE
        ///		   )
        ///	AND 
        ///		IIF(
        ///			@MinimumPeptideProphetProbability &lt;&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMassTagMatchCount {
            get {
                return ResourceManager.GetString("GetMassTagMatchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE dbo.GetMassTagsPassingFiltersWork
        ///(
        ///	@ConfirmedOnly tinyint = 0,				
        ///	@MinimumHighNormalizedScore float = 0,	
        ///	@MinimumPMTQualityScore decimal(9,5) = 0,
        ///	@MinimumHighDiscriminantScore real = 0,		
        ///	@MinimumPeptideProphetProbability real = 0
        ///)
        ///As		
        ///	
        ///SELECT 
        ///		Mass_Tag_ID
        ///FROM 
        ///		T_Mass_Tags AS MT	
        ///WHERE 
        ///		IIF( 
        ///			@MinimumPMTQualityScore &lt;&gt; 0,			
        ///				IIF( ISNULL(MT.PMT_Quality_Score)=TRUE, 0, MT.PMT_Quality_Score) &gt;= @MinimumPMTQualityScore,
        ///				TRUE
        ///		   )	
        ///	AND 
        ///		IIF( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMassTagsPassingFiltersWork {
            get {
                return ResourceManager.GetString("GetMassTagsPassingFiltersWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE GetMassTagsPlusPepProphetStats
        ///(
        ///	@ConfirmedOnly tinyint = 0,			
        ///	@MinimumHighNormalizedScore float = 0,	
        ///	@MinimumPMTQualityScore decimal = 0,	
        ///	@MinimumHighDiscriminantScore real = 0,		
        ///	@MinimumPeptideProphetProbability real = 0
        ///)
        ///AS
        ///
        ///SELECT 
        ///	MT.Mass_Tag_ID as Mass_Tag_ID,
        ///	MT.Peptide,
        ///	MT.Monoisotopic_Mass, 
        ///	MTN.Avg_GANET as Net_Value_to_Use, 
        ///	MT.High_Normalized_Score,
        ///	MTN.StD_GANET, 
        ///	MT.Peptide_Obs_Count_Passing_Filter, 
        ///	MT.Mod_Count, 
        ///	MT.Mod_Description,
        ///	MT. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMassTagsPlusPepProphetStats {
            get {
                return ResourceManager.GetString("GetMassTagsPlusPepProphetStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE dbo.GetMassTagToProteinNameMap
        ///(
        ///	@ConfirmedOnly tinyint = 0,			
        ///	@MinimumHighNormalizedScore float = 0,		
        ///	@MinimumPMTQualityScore float = 0,		
        ///	@MinimumHighDiscriminantScore real = 0,		
        ///	@MinimumPeptideProphetProbability real = 0	
        ///)
        ///AS    
        ///  SELECT  
        ///  	
        ///      PNM.Mass_Tag_ID,    
        ///      IIF( 
        ///        IIF(IsNull(PNM.Protein_DB_ID) = FALSE,PNM.Protein_DB_ID,-1) = 0,    
        ///           PNM.External_Protein_ID,
        ///           PNM.External_Reference_ID) 
        ///      AS Protein_ID,
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMassTagToProteinNameMap {
            get {
                return ResourceManager.GetString("GetMassTagToProteinNameMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE dbo.V_IFC_Mass_Tag_to_Protein_Name_Map
        ///
        ///AS    
        ///  SELECT 
        ///	MTPM.Mass_Tag_ID,
        ///	Prot.Ref_ID AS Internal_Ref_ID,
        ///	Prot.Protein_DB_ID,
        ///	Prot.External_Reference_ID,
        ///	Prot.External_Protein_ID,
        ///	Prot.Reference, 
        ///	Prot.Description, 
        ///	Prot.Protein_Residue_Count,
        ///	Prot.Monoisotopic_Mass
        ///  FROM 
        ///	T_Mass_Tag_to_Protein_Map AS MTPM
        ///	INNER JOIN 
        ///		T_Proteins AS Prot 
        ///	ON 
        ///		MTPM.Ref_ID=Prot.Ref_ID;
        ///
        ///.
        /// </summary>
        internal static string V_IFC_Mass_Tag_to_Protein_Name_Map {
            get {
                return ResourceManager.GetString("V_IFC_Mass_Tag_to_Protein_Name_Map", resourceCulture);
            }
        }
    }
}
